---
title: Essai de modélisation de la situation du Chavalier Cuivré (*Moxostoma hubbsi*)

# Use letters for affiliations, numbers to show equal authorship (if applicable) and to indicate the corresponding author
author:
  - name: Tristan Plasse
    affiliation: a,1
  - name: Yohan Wegener
    affiliation: a,2
address:
  - code: a
    address: Université de Sherbrooke, Biologie, Sherbrooke, Québec, J1K 2R1
    
corresponding_author:
  - code: 1
    text: "Tristan.Plasse@USherbrooke.ca"
  - code: 2
    text: "Yohan.Wegener@USherbrooke.ca"   

abstract: |
  Ce travail se voit être une suite logique aux recherches effectuées sur l'état de la population de Chevalier cuivré (*Moxostoma hubbsi*), espèce endémique du Québec et considérée menacée. Des estimations stochastiques basées sur des matrices de leslie à 33 stades distincts ont été éffectuées par Bannester & al. (2025). Nous avons bâtit un modèle de matrice de levkovitch à 3 stades pour estimer s'il est possible d'arriver à des résultats aussi concluants avec une méthode simplifiée. Notre méthode s'est avérée concuante et les résultats obtenus indiquent les mêmes tendances que ceux obtenus précédement par Bannester & al.(2025). L'on peut donc estimer qu'une matrice de levkovich est suffisante pour modéliser une PVA et qu'une matrice de leslie n'est pas une nécéssité.

keywords:
  - Chevalier Cuivré
  - Population
  - Menacée
  - Ensemencement

## must be one of: pnasresearcharticle (usual two-column layout), pnasmathematics (one column layout), or pnasinvited (invited submissions only)
pnas_type: pnasresearcharticle

bibliography: pnas-sample.bib
csl: pnas.csl

## change to true to add optional line numbering
lineno: false

output: rticles::pnas_article
---


Le Chevalier cuivré est une espèce de poisson d'eau douce endémique au Québec. Restreint à certaines zones du fleuve Saint-Laurent et à la rivière Richelieu, les populations sont précaires. La destruction de son habitat en est la cause principale.Seulement deux frayères sont connues à ce jour, et peu de mesures particulières ne sont mises en place pour les préserver dans le futur. Actuellement, des ensemencements sont effectuées à chaque année pour tenter de préserver une population viable. Plus de 14 000 larves et 230 000 alevins sont ainsi enscemencés dans la rivière Richelieu chaque année pour palier à un taux de recrutement très faible. Une des principale difficultées concernant la conservation de cette espèce est le grand manque de connaissances biologiques sur son histoire de vie. Une étude de XXX a été réalisée pour estimer la viabilité de la population à long terme de l'espèce selon 3 scénarios distincs qui prennent en compte la situation actuelle de l'espèce (source). Cette étude a utilisé un modèle de matrice de leslie à 33 stades pour effectuer une PVA et pour estimer l'effet de l'enscemencement à long terme sur la population. Notre objectif pour ce travail est de répéter leurs analyses tout en construisant un modèle plus simple de matrice de levkovich à 3 stades seulement.  




Méthodologie {.unnumbered}
========================================

Les données de bases ont directement été tirées de l'article de Bannester & al.(2025). Elles se présentes sous la forme d'une matrices de leslie à 33 satdes où la sous-diagonales représente les survies de chaque stade et où la fécondité est représentée par la première rangée (Fig 1). Nous avons choisi de simplifier cette matrice en matrice de levkovich à 3 stades. Les trois stades intra-annuels de la matrice de leslie originale, représentés par les termes "eggs", "larvae" et "fry", forment notre premier stade nommé "Juvéniles". Les stades 1 à 13, corespondants aux individus adultes non reproducteurs, ont été agréggés pour former notre deuxième stade nommé "Jeunes adultes". Puis, les stades 14 à 33, correspondants aux individus adultes reproducteurs, ont été agréggés dans un troisième stade nommé "Adultes". La fécondité des individus reproducteurs a été estimée en faisant la moyenne des fécondités des stades 13 à 14.Comme dans l'étude de Bannester & al.(2025), la fécondité du stade reproducteur comporte une portion de variabilité ajoutée dûe à la stochasticité. Cette variabilité à été ajouté en assumant que la fécondité annuelle des individus variait selon une loi normale ayant une moyenne de 0 et un écart-type de 0,25. Ainsi, la fécondité des individus varie entre aucun oeuf par année jusqu'au double de la moyenne annuelle. Contrairement à l'étude de Bannester & al.(2025),où chaque classe d'âge subissait une variabilité différente annuellement, tous les individus subissent la même variabilité au niveau de la fécondité annuelle. Pour la variabilité concernant les taux de survie, la méthode utilisée est celle de Bannester & al.(2025), où l'on assume que ces taux suivent une distribution beta. 



MÉTHODOLOGIE STASES ET SURVIE, MÉTHODOLOGIE STOCHASTICITÉ survie & stase.

Résultats {#author-affiliations .unnumbered}
-------------------

Include department, institution, and complete address, with the
ZIP/postal code, for each author. Use lower case letters to match
authors with institutions, as shown in the example. Authors with an
ORCID ID may supply this information at submission.

Discussion {#submitting-manuscripts .unnumbered}
----------------------

All authors must submit their articles at
[PNAScentral](http://www.pnascentral.org/cgi-bin/main.plex). If you are
using Overleaf to write your article, you can use the "Submit to PNAS"
option in the top bar of the editor window.



<!-- Leave these lines as they are at the end of your .Rmd file to ensure placement of methods & acknowledgements sections before the references-->
\showmatmethods
\showacknow
\pnasbreak
